#spring.servlet.multipart.max-file-size: 파일의 최대 사이즈 (default: 1MB)
#spring.servlet.multipart.max-request-size: 요청의 최대 사이즈 (default: 10MB)
spring:
  servlet:
    multipart:
      file-size-threshold: 1MB
      location: C:/Temp
      max-file-size: 100MB
      max-request-size: 100MB
